substitutions:
  device_name: esp-p1reader

esphome:
  name: ${device_name}
  comment: "P1 module to read smart meter"
  name_add_mac_suffix: false
  project:
    name: p1reader.esp-p1reader-component
    version: "1.0"

esp8266:
  board: d1_mini  # Use d1_mini to match your actual board type from the error log
  restore_from_flash: true
  flash_size: 4MB
  framework:
    version: recommended
    source: ~
  board_flash_mode: dout  # Try with dout mode which is more compatible

external_components:
  # Replace with your actual GitHub username and repository
  - source: github://yourusername/esphome-p1reader@main
# source: ../esphome-components is a reference to where in your HA config folder you put the contents of that repo folder relative to the YAML file
# source: github://xxx/esphome-p1reader@main to pull from branch main in the github repo called esphome-p1reader by the user xxx ()

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-p1reader"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO  # Logging costs performnce, swithc to DEBUG when needed
  baud_rate: 0 # disable logging over uart (would use up a HW uart)
  esp8266_store_log_strings_in_flash: true # Store logs in flash to save RAM
  
# Enable Home Assistant APIINFO ESPHome 2025.8.0
INFO Reading configuration /config/esphome/energymeter.yaml...
INFO Detected timezone 'Europe/Amsterdam'
INFO Generating C++ source...
INFO Compiling app...
Processing energymeter (board: d1_mini; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP @ 2.0.0
|-- ESP8266WiFi @ 1.0
|-- ESPAsyncWebServer @ 3.7.10
|-- DNSServer @ 1.1.1
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.10
|-- ArduinoJson @ 7.4.2
RAM:   [======    ]  57.5% (used 47080 bytes from 81920 bytes)
Flash: [=====     ]  49.1% (used 512509 bytes from 1044464 bytes)
========================= [SUCCESS] Took 2.39 seconds =========================
INFO Successfully compiled program.
INFO Uploading to 192.168.2.185
INFO Connecting to 192.168.2.185 port 8266...
INFO Connected to 192.168.2.185
INFO Uploading /data/build/energymeter/.pioenvs/energymeter/firmware.bin (516656 bytes)
INFO Compressed to 365787 bytes
ERROR Error binary size: Unknown error from ESP
api:
  encryption:
    key: !secret encryption_key
    
ota:
  password: !secret ota_password
  platform: esphome
  
uart:
  id: uart_bus
  tx_pin: TX
  rx_pin:
    number: RX
    inverted: true    # Most P1 meters require inverted signal
  baud_rate: 115200
  rx_buffer_size: 2048    # Reduced from 3072 to save memory

p1reader:
  - id: p1reader_esp
    uart_id: uart_bus
    # Explicitly set buffer size to a smaller value
    buffer_size: 2048
    protocol: ascii  # Use ASCII protocol explicitly

sensor:
  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_import:
      name: "Cumulative Active Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_export:
      name: "Cumulative Active Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_reactive_import:
      name: "Cumulative Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_reactive_export:
      name: "Cumulative Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import:
      name: "Momentary Active Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export:
      name: "Momentary Active Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import:
      name: "Momentary Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export:
      name: "Momentary Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import_l1:
      name: "Momentary Active Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export_l1:
      name: "Momentary Active Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import_l2:
      name: "Momentary Active Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export_l2:
      name: "Momentary Active Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import_l3:
      name: "Momentary Active Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export_l3:
      name: "Momentary Active Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import_l1:
      name: "Momentary Reactive Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import_l2:
      name: "Momentary Reactive Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import_l3:
      name: "Momentary Reactive Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export_l1:
      name: "Momentary Reactive Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export_l2:
      name: "Momentary Reactive Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export_l3:
      name: "Momentary Reactive Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    voltage_l1:
      name: "Voltage Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    voltage_l2:
      name: "Voltage Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    voltage_l3:
      name: "Voltage Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    current_l1:
      name: "Current Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    current_l2:
      name: "Current Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    current_l3:
      name: "Current Phase 3"

  # DSMR tariff-specific readings (T1/T2)
  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_import_t1:
      name: "Day Import (T1)"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      
  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_import_t2:
      name: "Night Import (T2)"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      
  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_export_t1:
      name: "Day Export (T1)"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      
  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_export_t2:
      name: "Night Export (T2)"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      
  # Gas and water consumption if available
  - platform: p1reader
    p1reader_id: p1reader_esp
    gas_consumption:
      name: "Gas Consumption"
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      
  - platform: p1reader
    p1reader_id: p1reader_esp
    water_consumption:
      name: "Water Consumption"
      unit_of_measurement: "m³"
      accuracy_decimals: 3
