substitutions:
  device_name: esp-p1readerhdlc

esphome:
  name: ${device_name}
  comment: "P1 module to read smart meter"
  name_add_mac_suffix: false
  project:
    name: p1reader.esp-p1readerhdlc-component
    version: "1.0"

esp8266:
  board: nodemcu
  restore_from_flash: true

external_components:
  - source: ../esphome-components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-p1readerhdlc"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO  # Logging costs performance, switch to DEBUG when needed only
  baud_rate: 0 # disable logging over uart (would use up a HW uart)
  esp8266_store_log_strings_in_flash: false # Avoid flash wear and tear
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key
    
ota:
  password: !secret ota_password

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200
  rx_buffer_size: 3072    # Buffer size controls polling frequency

p1reader:
  - id: p1reader_hdlc
    uart_id: uart_bus
#    buffer_size: 3072
    protocol: hdlc

sensor:
  - platform: p1reader
    p1reader_id: p1reader_hdlc
    cumulative_active_import:
      name: "Cumulative Active Import"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    cumulative_active_export:
      name: "Cumulative Active Export"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    cumulative_reactive_import:
      name: "Cumulative Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    cumulative_reactive_export:
      name: "Cumulative Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_import:
      name: "Momentary Active Import"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_export:
      name: "Momentary Active Export"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_import:
      name: "Momentary Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_export:
      name: "Momentary Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_import_l1:
      name: "Momentary Active Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_export_l1:
      name: "Momentary Active Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_import_l2:
      name: "Momentary Active Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_export_l2:
      name: "Momentary Active Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_import_l3:
      name: "Momentary Active Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_active_export_l3:
      name: "Momentary Active Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_import_l1:
      name: "Momentary Reactive Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_import_l2:
      name: "Momentary Reactive Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_import_l3:
      name: "Momentary Reactive Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_export_l1:
      name: "Momentary Reactive Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_export_l2:
      name: "Momentary Reactive Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    momentary_reactive_export_l3:
      name: "Momentary Reactive Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    voltage_l1:
      name: "Voltage Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    voltage_l2:
      name: "Voltage Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    voltage_l3:
      name: "Voltage Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    current_l1:
      name: "Current Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    current_l2:
      name: "Current Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_hdlc
    current_l3:
      name: "Current Phase 3"
